// src/controllers/empleadoController.js
// ...
export const createEmpleado = async (req, res) => {
    const { nombre, apellido, dni, telefono, email } = req.body;
    const foto = req.file ? `/public/uploads/${req.file.filename}` : ''; // <-- Acceder a req.file
    // ...
};
// ...